In [14]:
# 모듈 로딩 ---------------------------------------------------------------------------------------
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import numpy as np

In [15]:
import	platform

# 시스템별 한글 폰트 설정
if	platform.system()	==	'Windows':
    plt.rc('font', family='Malgun Gothic')
elif platform.system()	==	'Darwin':	#	MacOS
    plt.rc('font', family='AppleGothic')
else:
    plt.rc('font', family='AppleGothic')

[1] 데이터 로딩

In [16]:
data, target = load_iris(as_frame = True, return_X_y= True)

[2] 학습 데이터 준비

In [17]:
# 데이터 => petal_length, petal_width
# 타겟 => 0, 2

data = data.loc[:,data.columns[2:]]
data

petal length (cm)  petal width (cm)
0                  1.4               0.2
1                  1.4               0.2
2                  1.3               0.2
3                  1.5               0.2
4                  1.4               0.2
..                 ...               ...
145                5.2               2.3
146                5.0               1.9
147                5.2               2.0
148                5.4               2.3
149                5.1               1.8

[150 rows x 2 columns]

In [18]:
# 학습용, 테스트용 데이터 분리
from sklearn.model_selection import train_test_split

train_data, test_data, train_target, test_target = train_test_split(
    data, target, test_size = 0.2, random_state=42
)

In [19]:
train_data

petal length (cm)  petal width (cm)
22                 1.0               0.2
15                 1.5               0.4
65                 4.4               1.4
11                 1.6               0.2
42                 1.3               0.2
..                 ...               ...
71                 4.0               1.3
106                4.5               1.7
14                 1.2               0.2
92                 4.0               1.2
102                5.9               2.1

[120 rows x 2 columns]

In [20]:
model = LogisticRegression(multi_class = 'multinomial')
model.fit(train_data, train_target)

LogisticRegression(multi_class='multinomial')

In [21]:
model.predict([[10, 3]])

c:\Users\LJH\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([2])

In [22]:
model.coef_

array([[-2.59489149, -1.09019953],
       [ 0.07420011, -0.74788769],
       [ 2.52069138,  1.83808723]])

In [23]:
point = np.arange(1, 7, 0.1)

In [24]:
model.predict_proba([[3,4]])

c:\Users\LJH\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[0.02740208, 0.1827516 , 0.78984632]])

### 시그모이드 함수 / 소프트 맥스 후 결과 확인

In [25]:
from scipy.special import softmax, expit
ret = model.decision_function([[3,4]])
sigValue2 = softmax(ret)
sigValue2

c:\Users\LJH\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[0.02740208, 0.1827516 , 0.78984632]])

In [26]:
ret

array([[-1.75290953,  0.1445995 ,  1.60831003]])