모델 생성 시 랜덤으로 초기화되는 W, b 값 고정

In [14]:
from tensorflow.keras import models, layers
import numpy as np
from tensorflow import random

In [15]:
# 임시 테스트 데이터
X = np.array([[2,0],[3,0],[4,3],[5,1],[6,1],[7,0],[8,2]])
y = np.array([52, 56, 71, 77, 82, 94, 100])

In [16]:
X.shape, y.shape

((7, 2), (7,))

**모델 구상**

In [17]:
## W, b 초기값 고정
random.set_seed(11)

In [18]:
model = models.Sequential()
model.add(layers.Dense(15, activation = 'relu', input_shape = (2,)))
model.add(layers.Dense(1, activation = 'linear'))

In [19]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 15)                45        
                                                                 
 dense_3 (Dense)             (None, 1)                 16        
                                                                 
Total params: 61
Trainable params: 61
Non-trainable params: 0
_________________________________________________________________


**모델 속성 확인**

In [20]:
# 모델의 layer 객체 리스트로 확인
L1 = model.layers[0]

In [21]:
L1.weights

[<tf.Variable 'dense_2/kernel:0' shape=(2, 15) dtype=float32, numpy=
 array([[-0.29631114,  0.37537187, -0.24640921,  0.5142406 ,  0.31416845,
         -0.41857034, -0.19999248, -0.58546865, -0.3554358 ,  0.58291185,
         -0.12107381,  0.3238395 , -0.06760222, -0.02177614,  0.05121469],
        [ 0.3202483 ,  0.16437584, -0.42809546, -0.22091794,  0.47248828,
         -0.02519327, -0.32629982,  0.12834728,  0.30775893,  0.09019065,
          0.07265884, -0.48352158, -0.19885129, -0.11066794, -0.15434334]],
       dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(15,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>]

In [22]:
L1.weights[0]

<tf.Variable 'dense_2/kernel:0' shape=(2, 15) dtype=float32, numpy=
array([[-0.29631114,  0.37537187, -0.24640921,  0.5142406 ,  0.31416845,
        -0.41857034, -0.19999248, -0.58546865, -0.3554358 ,  0.58291185,
        -0.12107381,  0.3238395 , -0.06760222, -0.02177614,  0.05121469],
       [ 0.3202483 ,  0.16437584, -0.42809546, -0.22091794,  0.47248828,
        -0.02519327, -0.32629982,  0.12834728,  0.30775893,  0.09019065,
         0.07265884, -0.48352158, -0.19885129, -0.11066794, -0.15434334]],
      dtype=float32)>