# Pytorch
---  

#### [1] Tensor 생성

In [36]:
import torch

In [37]:
# 버전 확인
torch.__version__

'1.12.1'

In [38]:
## [기본] tensor(data)
t1 = torch.tensor([1,2,3,])

In [39]:
type(t1), t1.shape, t1.dtype, t1.device

(torch.Tensor, torch.Size([3]), torch.int64, device(type='cpu'))

In [40]:
## tensor(data), 타입 지정
t2 = torch.tensor([1,2,3], dtype=torch.int32)

In [41]:
type(t2), t2.shape, t2.dtype, t2.device

(torch.Tensor, torch.Size([3]), torch.int32, device(type='cpu'))

In [42]:
## tensor(data), 타입 지정(하나만 .을 찍어 확인하는 경우)
t3 = torch.tensor([1.,2,3])

In [43]:
# 하나만 float 을 찍었는데도 모두다 float 타입으로 통일됨
type(t3), t3.shape, t3.dtype, t3.device

(torch.Tensor, torch.Size([3]), torch.float32, device(type='cpu'))

In [44]:
## tensor(data), 2차원으로 만들기
t4 = torch.tensor([[1.,2,3], [1,2,3]])

In [45]:
type(t4), t4.shape, t4.dtype, t4.device

(torch.Tensor, torch.Size([2, 3]), torch.float32, device(type='cpu'))

In [46]:
t5 = torch.zeros(size=(10,3))

In [47]:
type(t5), t5.shape, t5.dtype, t5.device

(torch.Tensor, torch.Size([10, 3]), torch.float32, device(type='cpu'))

In [48]:
t6 = torch.zeros_like(t4)

In [49]:
type(t6), t6.shape, t6.dtype, t6.device

(torch.Tensor, torch.Size([2, 3]), torch.float32, device(type='cpu'))

In [50]:
t6

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [51]:
import random

random.seed(10)

In [52]:
t7 = torch.rand_like(t4)

In [53]:
type(t7), t7.shape, t7.dtype, t7.device

(torch.Tensor, torch.Size([2, 3]), torch.float32, device(type='cpu'))

In [54]:
t7

tensor([[0.1024, 0.1484, 0.4979],
        [0.8243, 0.1199, 0.0101]])

random.seed 안먹힘

### Indexing & Slicing

In [60]:
# 리스트랑 비슷함
# 행 뽑기
t4[0]

tensor([1., 2., 3.])

In [61]:
# 열 뽑기
t4[:, 0]

tensor([1., 1.])

In [63]:
# 행 방향으로 합치기
t123 = torch.cat([t1,t2,t3], dim = 0)

In [64]:
t123

tensor([1., 2., 3., 1., 2., 3., 1., 2., 3.])

In [66]:
# 최대값 최소값 찾기
t123.max(), t123.min()

(tensor(3.), tensor(1.))

In [67]:
torch.cuda.is_available()

False